name: project6
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.2
  flutter_riverpod: ^2.6.1
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  percent_indicator: ^4.2.2
  flutter_localization: ^0.3.2
  intl: ^0.20.2
  flutter_secure_storage: ^9.2.4
  riverpod_annotation: ^2.6.1
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  dropdown_search: ^5.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_generator: ^2.6.4
  json_serializable: ^6.7.1

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/GeStock.jpeg"



flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/database/Gestock.db


